mod amazon_bedrock;
mod auth;
mod bearer_auth_provider;
mod models_endpoint;
mod provider;
mod shared_state;
mod universal;
mod universal_catalog;
mod universal_registry;
mod universal_session;

pub use amazon_bedrock::is_supported_amazon_bedrock_region;
pub use auth::AgentIdentitySessionFallback;
pub use auth::ProviderAuthScope;
pub use auth::ResolvedProviderAuth;
pub use auth::auth_provider_from_auth;
pub use auth::auth_provider_from_auth_manager;
pub use auth::unauthenticated_auth_provider;
pub use bearer_auth_provider::BearerAuthProvider;
pub use bearer_auth_provider::BearerAuthProvider as CoreAuthProvider;
pub use codex_model_contract::ModelCapabilities;
pub use codex_model_contract::ModelDescriptor;
pub use codex_model_contract::ModelError;
pub use codex_model_contract::ModelEvent;
pub use codex_model_contract::ModelFeature;
pub use codex_model_contract::ModelRequest;
pub use codex_model_contract::ModelResponse;
pub use codex_model_contract::ModelSession;
pub use codex_model_provider_info::AMAZON_BEDROCK_PROVIDER_ID;
pub use codex_model_provider_info::AMAZON_BEDROCK_RUNTIME_PROVIDER_ID;
pub use codex_model_provider_info::CHATGPT_CODEX_BASE_URL;
pub use codex_protocol::account::ProviderAccount;
pub use provider::ModelProvider;
pub use provider::ModelProviderFuture;
pub use provider::ProviderAccountError;
pub use provider::ProviderAccountResult;
pub use provider::ProviderAccountState;
pub use provider::ProviderAuthRecoveryMessages;
pub use provider::ProviderCapabilities;
pub use provider::ProviderUnauthorizedRecovery;
pub use provider::RemoteCompactionSupport;
pub use provider::SharedModelProvider;
pub use provider::create_model_provider;
pub use universal::ModelContractAdapter;
pub use universal_catalog::ModelCatalog;
pub use universal_registry::ModelProviderRegistry;
pub use universal_registry::SelectedModel;
pub use universal_registry::build_universal_registry;
