#!/usr/bin/env python3
"""Regenerate the experimental precomputed export zst for RWO-006.

Generalized successor of the proven RWO-005 replication script: adds enum
support (ts union of quoted serde names; json oneOf per variant) and a
multi-method batch. Format rules identical (ts-rs 11.1.0 + schemars 0.8.22
semantics re-derived from the vendored tree + generator sources; RWO-005
zero-collateral precedent).

Adds 4 methods (workflow/improve/{propose,validate,approve,publish} — macro
order after workflow/fork), 15 types, 4 method schema files, arms + defs in
both bundles and the standalone ClientRequest.json.
"""

import io
import json
import re

import zstandard

SCHEMA = (
    "app-server-protocol/schema/precomputed/app-server-exports-experimental.json.zst"
)
SRC = "app-server-protocol/src/protocol/v2/workflow.rs"
COMMON = "app-server-protocol/src/protocol/common.rs"

HEADER = (
    "// GENERATED CODE! DO NOT MODIFY BY HAND!\n\n"
    "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/"
    "ts-rs). Do not edit this file manually.\n\n"
)

# ------------------------------------------------------------------ extraction


def camel(s):
    p = s.split("_")
    return p[0] + "".join(x[:1].upper() + x[1:] for x in p[1:])


def find_block(lines, pat):
    for i, ln in enumerate(lines):
        if pat.match(ln):
            return i
    return None


def docs_above(lines, i, indent):
    docs = []
    j = i - 1
    pre = " " * indent + "///"
    attr = " " * indent + "#["
    while j >= 0 and (lines[j].startswith(pre) or lines[j].startswith(attr)):
        if lines[j].startswith(pre):
            docs.insert(0, lines[j][len(pre) :])
        j -= 1
    return docs


def extract_struct(src, name):
    lines = src.splitlines()
    i = find_block(lines, re.compile(r"^pub struct " + name + r" \{"))
    if i is None:
        raise SystemExit(f"struct {name} not found")
    docs = docs_above(lines, i, 0)
    # deny_unknown_fields on the serde attr <=> the JSON schema carries
    # additionalProperties: false (verified: WorkflowEvidenceReference
    # lacks it and its real schema lacks additionalProperties; 585 v2
    # object defs follow the rule).
    deny = False
    j = i - 1
    while j >= 0 and lines[j].startswith("#["):
        if "deny_unknown_fields" in lines[j]:
            deny = True
        j -= 1
    fields = []
    k = i + 1
    while not lines[k].startswith("}"):
        if lines[k].startswith("    pub "):
            fdocs = docs_above(lines, k, 4)
            fname = camel(lines[k][8:].split(":")[0].strip())
            ftype = lines[k].split(":", 1)[1].strip().rstrip(",")
            fields.append((fname, ftype, fdocs))
        k += 1
    return "struct", name, docs, fields, deny


def extract_enum(src, name):
    lines = src.splitlines()
    i = find_block(lines, re.compile(r"^pub enum " + name + r" \{"))
    if i is None:
        raise SystemExit(f"enum {name} not found")
    docs = docs_above(lines, i, 0)
    # rename_all on the enum itself
    ren = "camelCase"
    j = i - 1
    while j >= 0 and lines[j].startswith("#["):
        m = re.search(r'rename_all = "(\w+)"', lines[j])
        if m:
            ren = m.group(1)
        j -= 1
    variants = []
    k = i + 1
    while not lines[k].startswith("}"):
        m = re.match(r"^    (\w+),$", lines[k])
        if m:
            vdocs = docs_above(lines, k, 4)
            vname = m.group(1)
            # serde/ts-rs camelCase for (PascalCase) variant names
            # lowercases the first character: DefinitionDelta ->
            # definitionDelta (verified against original enums:
            # accessKeys, pendingInit, spawnAgent, ...).
            wire = {
                "camelCase": vname[:1].lower() + vname[1:],
                "kebab-case": vname.replace("_", "-"),
            }.get(ren, vname)
            # explicit rename on the variant wins
            vj = k - 1
            while (
                vj > i
                and lines[vj].startswith("    #[")
                and not lines[vj].startswith("    #[doc")
                and not lines[vj].startswith("    ///")
            ):
                mr = re.search(r'rename = "([^"]+)"', lines[vj])
                if mr:
                    wire = mr.group(1)
                vj -= 1
            variants.append((vname, wire, vdocs))
        k += 1
    return "enum", name, docs, variants, False


# ------------------------------------------------------------------ ts side


def ts_type(rust):
    t = rust.strip()
    if t == "String":
        return "string", False
    if t == "bool":
        return "boolean", False
    if t.startswith("Option<") and t.endswith(">"):
        return ts_type(t[7:-1])[0], True
    if t.startswith("Vec<") and t.endswith(">"):
        return f"Array<{ts_type(t[4:-1])[0]}>", False
    return t, False


def ts_docs(docs):
    if not docs:
        return ""
    out = "/**\n"
    for i, d in enumerate(docs):
        out += " *" + d
        if i < len(docs) - 1:
            out += "\n"
    return out + "\n */\n"


def deps_of(fields):
    out = set()
    for _, ft, _ in fields:
        t = ft.strip()
        while t.startswith(("Vec<", "Option<")) and t.endswith(">"):
            t = t[t.index("<") + 1 : -1].strip()
        if t[:1].isupper() and t not in ("String",):
            out.add(t)
    return out


def gen_struct_ts(name, docs, fields):
    imports = "".join(
        f'import type {{ {d} }} from "./{d}";\n' for d in sorted(deps_of(fields))
    )
    out = HEADER
    if imports:
        out += imports + "\n"
    out += ts_docs(docs)
    out += f"export type {name} = {{\n"
    for i, (fname, ftype, fdocs) in enumerate(fields):
        out += ts_docs(fdocs)
        t, optional = ts_type(ftype)
        out += f"{fname}{'?' if optional else ''}: {t}{' | null' if optional else ''},"
        if i < len(fields) - 1:
            out += "\n"
    return out + " };\n"


def gen_enum_ts(name, docs, variants):
    out = HEADER
    out += ts_docs(docs)
    union = " | ".join(f'"{w}"' for _, w, _ in variants)
    return out + f"export type {name} = {union};\n"


# ------------------------------------------------------------------ json side


def para_join(docs):
    paras, cur = [], []
    for d in docs:
        if d.strip() == "":
            paras.append(" ".join(x.strip() for x in cur))
            cur = []
        else:
            cur.append(d.strip())
    paras.append(" ".join(x.strip() for x in cur))
    return "\n\n".join(p for p in paras if p)


def json_field(ftype, fdocs):
    t = ftype.strip()
    desc = para_join(fdocs) if fdocs else None
    if t == "String":
        s = {"type": "string"}
    elif t == "bool":
        s = {"type": "boolean"}
    elif t.startswith("Option<") and t.endswith(">"):
        inner = json_field(t[7:-1], None)
        if "$ref" in inner:
            s = {"anyOf": [inner, {"type": "null"}]}
        else:
            s = {"type": [inner["type"], "null"]}
    elif t.startswith("Vec<") and t.endswith(">"):
        s = {"type": "array", "items": json_field(t[4:-1], None)}
    else:
        s = {"$ref": "#/definitions/" + t}
    if desc:
        s = dict(s)
        s["description"] = desc
    return s


def struct_schema(kind, name, docs, members, *, root, ns_defs=None, deny=False):
    props = {}
    required = []
    for fname, ftype, fdocs in members:
        props[fname] = json_field(ftype, fdocs)
        if not ftype.strip().startswith("Option<"):
            required.append(fname)
    out = {}
    if root:
        out["$schema"] = "http://json-schema.org/draft-07/schema#"
    if ns_defs:
        out["definitions"] = ns_defs
    desc = para_join(docs)
    if desc:
        out["description"] = desc
    if deny:
        out["additionalProperties"] = False
    out["properties"] = props
    out["required"] = sorted(required)
    if root:
        out["title"] = name
    out["type"] = "object"
    return out


def enum_schema(kind, name, docs, variants, *, root):
    out = {}
    if root:
        out["$schema"] = "http://json-schema.org/draft-07/schema#"
    desc = para_join(docs)
    if desc:
        out["description"] = desc
    out["oneOf"] = [
        ({"description": para_join(vdocs)} if vdocs else {})
        | {"enum": [wire], "type": "string"}
        for _, wire, vdocs in variants
    ]
    return out


def schema_of(spec, *, root, ns_defs=None):
    kind, name, docs, members, deny = spec
    if kind == "enum":
        return enum_schema(kind, name, docs, members, root=root)
    return struct_schema(
        kind, name, docs, members, root=root, ns_defs=ns_defs, deny=deny
    )


def namespaced(obj, ns):
    return json.loads(
        re.sub(
            r'"\$ref": "#/definitions/(\w+)"',
            rf'"$ref": "#/definitions/{ns}\1"',
            json.dumps(obj),
        )
    )


def method_arm(method, doc, params, ns):
    return {
        "description": doc,
        "properties": {
            "id": {"$ref": f"#/definitions/{ns}RequestId"},
            "method": {"enum": [method], "title": arm_title(method), "type": "string"},
            "params": {"$ref": f"#/definitions/{ns}{params}"},
        },
        "required": ["id", "method", "params"],
        "title": arm_title(method)[:-6],
        "type": "object",
    }


def arm_title(method):
    # "workflow/improve/propose" -> "Workflow/improve/proposeRequestMethod"
    family, _, rest = method.partition("/")
    return f"{family.capitalize()}/{rest}RequestMethod"


def dump(obj):
    return json.dumps(obj, indent=1, sort_keys=True) + "\n"


# ------------------------------------------------------------------ main

METHODS = [
    ("workflow/improve/propose", "WorkflowImprovePropose"),
    ("workflow/improve/validate", "WorkflowImproveValidate"),
    ("workflow/improve/approve", "WorkflowImproveApprove"),
    ("workflow/improve/publish", "WorkflowImprovePublish"),
]
NESTED = [
    "WorkflowChangeKind",
    "WorkflowRunProvenance",
    "WorkflowEvidenceSummary",
    "WorkflowImprovementCandidate",
    "WorkflowValidationStageName",
    "WorkflowValidationStage",
    "WorkflowImprovementDecision",
    "WorkflowImprovementLineage",
]
ALL_TYPES = NESTED + [t + s for _, t in METHODS for s in ("Params", "Response")]


def main():
    src = open(SRC).read()
    common = open(COMMON).read()
    data = json.loads(
        zstandard.ZstdDecompressor()
        .stream_reader(io.BytesIO(open(SCHEMA, "rb").read()))
        .read()
    )
    ts, js = data["typescript"], data["json_schema"]

    S = {}
    for n in ALL_TYPES:
        try:
            S[n] = extract_struct(src, n)
        except SystemExit:
            S[n] = extract_enum(src, n)

    # 1) ts files
    for n, spec in S.items():
        kind, _, docs, members, _deny = spec
        ts[f"v2/{n}.ts"] = (
            gen_enum_ts(n, docs, members)
            if kind == "enum"
            else gen_struct_ts(n, docs, members)
        )

    # 2) index lines
    if "WorkflowChangeKind }" not in ts["v2/index.ts"]:
        lines = ts["v2/index.ts"].splitlines(keepends=True)
        adds = {n: f'export type {{ {n} }} from "./{n}";\n' for n in ALL_TYPES}
        out, placed = [], set()
        for l in lines:
            m = re.search(r"export type \{ (\w+) \}", l)
            if m:
                for n in sorted(adds):
                    if n not in placed and n < m.group(1):
                        out.append(adds[n])
                        placed.add(n)
            out.append(l)
        for n in sorted(adds):
            if n not in placed:
                out.append(adds[n])
        ts["v2/index.ts"] = "".join(out)

    # 3) ClientRequest.ts arms (after workflow/fork)
    if '"workflow/improve/propose"' not in ts["ClientRequest.ts"]:
        crts = ts["ClientRequest.ts"]
        anchor = (
            '| { "method": "workflow/fork", id: RequestId, '
            "params: WorkflowForkParams, }"
        )
        assert anchor in crts
        arms = "".join(
            f'| {{ "method": "{m}", id: RequestId, params: {t}Params, }} '
            for m, t in METHODS
        )
        ts["ClientRequest.ts"] = crts.replace(anchor, anchor + " " + arms.strip(), 1)

    # 3b) ClientRequest.ts imports for the new params types. The real
    # generator emits one import per params type referenced by an arm
    # (root-level imports first, then ./v2/ imports, both alphabetical —
    # verified against the merged zst). This also repairs the RWO-005
    # gap: WorkflowForkParams was never imported.
    new_imports = {t + "Params" for _, t in METHODS} | {"WorkflowForkParams"}
    lines = ts["ClientRequest.ts"].splitlines(keepends=True)
    present = {
        re.search(r"\{ (\w+) \}", l).group(1)
        for l in lines
        if l.startswith("import type")
    }
    missing = sorted(n for n in new_imports if n not in present)
    if missing:
        first_v2 = next(
            i
            for i, l in enumerate(lines)
            if l.startswith("import type") and '"./v2/' in l
        )
        for n in missing:
            line = f'import type {{ {n} }} from "./v2/{n}";\n'
            at = next(
                (
                    i
                    for i in range(first_v2, len(lines))
                    if lines[i].startswith("import type")
                    and re.search(r"\{ (\w+) \}", lines[i]).group(1) > n
                ),
                None,
            )
            if at is None:
                # after the last v2 import
                at = (
                    max(
                        i
                        for i, l in enumerate(lines)
                        if l.startswith("import type") and '"./v2/' in l
                    )
                    + 1
                )
            lines.insert(at, line)
        ts["ClientRequest.ts"] = "".join(lines)

    # 4) method json files (root shape; definitions = transitive closure,
    # lazily extracting pre-existing referenced types from the same
    # source — e.g. WorkflowEvidenceReference / WorkflowInstanceStatus —
    # matching the real generator, which inlines every referenced type)
    def closure(tname, seen):
        if tname not in S:
            try:
                S[tname] = extract_struct(src, tname)
            except SystemExit:
                S[tname] = extract_enum(src, tname)
        if S[tname][0] == "struct":
            for _, ft, _ in S[tname][3]:
                base = ft.strip()
                while base.startswith(("Vec<", "Option<")) and base.endswith(">"):
                    base = base[base.index("<") + 1 : -1].strip()
                if base[:1].isupper() and base not in ("String",) and base not in seen:
                    seen.add(base)
                    closure(base, seen)
        return seen

    for m, t in METHODS:
        for suffix in ("Params", "Response"):
            name = t + suffix
            nested = {
                n: schema_of(S[n], root=False) for n in sorted(closure(name, set()))
            }
            js[f"v2/{name}.json"] = dump(
                schema_of(S[name], root=True, ns_defs=nested or None)
            )

    # method docs from common.rs registrations: the /// doc lines under
    # the #[experimental("...")] attribute, joined into one paragraph
    # (verified against the merged RWO-005 fork arm: two /// lines -> one
    # space-joined description).
    def method_doc(method):
        m = re.search(
            r'#\[experimental\("' + re.escape(method) + r'"\)\]\s*\n'
            r"((?:\s*///[^\n]*\n)+)",
            common,
        )
        if not m:
            raise SystemExit(f"no /// docs found for {method} in common.rs")
        docs = [ln.strip()[3:].strip() for ln in m.group(1).splitlines()]
        return " ".join(d for d in docs if d)

    # 5a) main bundle
    mb = json.loads(js["codex_app_server_protocol.schemas.json"])
    v2 = mb["definitions"]["v2"]
    for n in ALL_TYPES:
        v2[n] = namespaced(
            schema_of(S[n], root=(n.endswith(("Params", "Response")))), "v2/"
        )
    arms = mb["definitions"]["ClientRequest"]["oneOf"]
    if not any("workflow/improve/propose" in json.dumps(a) for a in arms):
        fi = next(
            i
            for i, a in enumerate(arms)
            if a["properties"]["method"]["enum"] == ["workflow/fork"]
        )
        for off, (m, t) in enumerate(METHODS):
            arms.insert(fi + 1 + off, method_arm(m, method_doc(m), t + "Params", "v2/"))
    js["codex_app_server_protocol.schemas.json"] = dump(mb)

    # 5b) flat v2 bundle
    vb = json.loads(js["codex_app_server_protocol.v2.schemas.json"])
    vd = vb["definitions"]
    for n in ALL_TYPES:
        vd[n] = schema_of(S[n], root=n.endswith(("Params", "Response")))
    varms = vd["ClientRequest"]["oneOf"]
    if not any("workflow/improve/propose" in json.dumps(a) for a in varms):
        fi = next(
            i
            for i, a in enumerate(varms)
            if a["properties"]["method"]["enum"] == ["workflow/fork"]
        )
        for off, (m, t) in enumerate(METHODS):
            varms.insert(fi + 1 + off, method_arm(m, method_doc(m), t + "Params", ""))
    js["codex_app_server_protocol.v2.schemas.json"] = dump(vb)

    # 5c) standalone ClientRequest.json
    cr = json.loads(js["ClientRequest.json"])
    cd = cr["definitions"]
    for m, t in METHODS:
        for n in sorted(closure(t + "Params", {t + "Params"})):
            if n not in cd:
                cd[n] = schema_of(S[n], root=False)
    carms = cr["oneOf"]
    if not any("workflow/improve/propose" in json.dumps(a) for a in carms):
        fi = next(
            i
            for i, a in enumerate(carms)
            if a["properties"]["method"]["enum"] == ["workflow/fork"]
        )
        for off, (m, t) in enumerate(METHODS):
            carms.insert(fi + 1 + off, method_arm(m, method_doc(m), t + "Params", ""))
    js["ClientRequest.json"] = dump(cr)

    # 6) RWO-005 fidelity repair (three proven defects in the merged zst):
    #   a) v2/WorkflowForkParams.json carries "$ref": "#/definitions/
    #      WorkflowForkAttribution" with NO definitions block (dangling
    #      ref — every one of the 166 original method files that
    #      reference types has a definitions block);
    #   b) the fork attribution/lineage entries lack their type-level
    #      docs everywhere (the real generator emits them: 182 original
    #      v2 types carry doc blocks, multi-paragraph as "p1\n\np2");
    #   c) ClientRequest.ts never imported WorkflowForkParams (repaired
    #      in step 3b).
    # Re-emit the two method json files fully (adds the definitions
    # block + descriptions) and the two nested types everywhere they
    # appear. Shapes otherwise proven identical by the fork self-test
    # (params/response/arm byte-identical regenerations).
    SF = {}
    for n in (
        "WorkflowForkParams",
        "WorkflowForkResponse",
        "WorkflowForkAttribution",
        "WorkflowForkLineage",
    ):
        try:
            SF[n] = extract_struct(src, n)
        except SystemExit:
            SF[n] = extract_enum(src, n)

    def transitive_in(sx, tname, seen):
        for _, ft, _ in sx[tname][3] if sx[tname][0] == "struct" else []:
            base = ft.strip()
            while base.startswith(("Vec<", "Option<")) and base.endswith(">"):
                base = base[base.index("<") + 1 : -1].strip()
            if base in sx and base not in seen:
                seen.add(base)
                transitive_in(sx, base, seen)
        return seen

    for name in ("WorkflowForkParams", "WorkflowForkResponse"):
        nested = {
            n: schema_of(SF[n], root=False)
            for n in sorted(transitive_in(SF, name, set()))
        }
        js[f"v2/{name}.json"] = dump(
            schema_of(SF[name], root=True, ns_defs=nested or None)
        )

    for n in ("WorkflowForkAttribution", "WorkflowForkLineage"):
        kind, _, docs, fields, _deny = SF[n]
        if not docs:
            continue
        ts[f"v2/{n}.ts"] = gen_struct_ts(n, docs, fields)
        sch = schema_of(SF[n], root=False)
        mb = json.loads(js["codex_app_server_protocol.schemas.json"])
        if n in mb["definitions"]["v2"]:
            mb["definitions"]["v2"][n] = namespaced(sch, "v2/")
        js["codex_app_server_protocol.schemas.json"] = dump(mb)
        vb = json.loads(js["codex_app_server_protocol.v2.schemas.json"])
        if n in vb["definitions"]:
            vb["definitions"][n] = sch
        js["codex_app_server_protocol.v2.schemas.json"] = dump(vb)
        cr = json.loads(js["ClientRequest.json"])
        if n in cr["definitions"]:
            cr["definitions"][n] = sch
        js["ClientRequest.json"] = dump(cr)

    # 7) repack
    payload = {
        "typescript": ts,
        "json_schema": js,
        "internal_json_schema": data["internal_json_schema"],
    }
    blob = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    packed = zstandard.ZstdCompressor(level=19).compress(blob)
    open(SCHEMA, "wb").write(packed)
    print(f"regenerated {SCHEMA}: {len(packed)} bytes (ts={len(ts)}, js={len(js)})")


if __name__ == "__main__":
    main()
